WebApp/Models/Permission.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Models
{
    public class Permission
    {
        [Column(TypeName ="id")]
        public string? Id {get;set;}
        [Column(TypeName ="name")]
        [MaxLength(150)]
        public string? Name {get;set;}
        [Column(TypeName ="description ")]
        public string? Description {get;set;}
        [Column(TypeName ="normalize_name")]
        public string? NormalizeName {get;set;}
        [JsonIgnore]
        public virtual ICollection<Role>? Roles {get;set;}
    }
}

WebApp/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApp.Data;
using WebApp.Dto.Category;
using WebApp.Models;
using WebApp.Service.Interface;

namespace WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ILogger<Category> _logger;
        private readonly ICategoryService _categoryService;

        public CategoryController(ILogger<Category> logger,ICategoryService categoryService)
        {
            _logger = logger;
            _categoryService = categoryService;
        }

        public async Task<ActionResult> Index(string search, string currentOrder,int? numPage,string currentFilter)
        {
            if(search !=null)
                numPage = 1;
            else
                search = currentFilter;
            
            ViewData["OrdenActual"] = currentOrder;
            ViewData["FiltroActual"] = search;
            var categories = _categoryService.All(search,currentOrder);

            return View(await Pagination<Category>.PaginationCreate(categories.AsNoTracking(),numPage??1,5));
        }
        public IActionResult New(){
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Store([Bind("Name","Description")]CategoryInDto category){
            if(!ModelState.IsValid){
                TempData["Error_data"]="Los datos de la categoria son incorrectos";
                return View("New",category);
            }
            
            var categoryOutDto = await _categoryService.Create(category);
            if(categoryOutDto == null){
                TempData["Error_data"]="Error al crear la categoria";
                return View("New",category);
            }

            TempData["Success_data"]="La categoria se ha creado correctamente";
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> Show(Guid id){
            var category = await _categoryService.FindById(id);
            
            if(category == null) return NotFound();
            return View(category);
        }
        public async Task<ActionResult> Edit(Guid id){
            var category = await _categoryService.Edit(id);
            
            if(category == null) return NotFound();
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(Guid id,[Bind("Id","Name","Description")]CategoryEditDto category){
            if(id != category.Id) return NotFound();
            if(!ModelState.IsValid) {
                
                TempData["Error_data"] ="El Intento de Actualizacion no Valido";
                return View("Edit",category);
                
                }
                try{
                    await _categoryService.Update(category);
                }catch(DbUpdateConcurrencyException){
                    if(!_categoryService.Exists(id)){
                        return NotFound();
                    }else{
                        TempData["Error_data"] ="El Intento de Actualizacion no Valido";
                        throw ;
                    }
                }
                
                TempData["Success_data"]="La categoria se a actualizado correctamente";
                return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Delete(Guid id){
            
            var category = await _categoryService.FindById(id);
            
            if(category == null) return NotFound();
            
        return View(category);
        }
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Destroy(Guid id){
            _categoryService.Destroy(id);
            TempData["Success_data"]="La categoria se ha eliminado correctamente";
            return RedirectToAction(nameof(Index));
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

    }
}

WebApp/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WebApp.Data;
using WebApp.Dto.Permission;
using WebApp.Models;
using WebApp.Service.Interface;

namespace WebApp.Controllers
{
    
    public class PermissionController : Controller
    {
        private readonly ILogger<PermissionController> _logger;
        private readonly IPermissionService _service;
        public PermissionController(ILogger<PermissionController> logger,IPermissionService service)
        {
            _logger = logger;
            _service = service;
        }
        
        [Authorize(Policy ="SuperUser")]
        public async Task<IActionResult> Index(int? numPage)
        {
            var permissions = _service.All();
            return View(await Pagination<Permission>.PaginationCreate(permissions.AsNoTracking(),numPage??1,5));
        }

        public async Task<IActionResult> Show(string id){
            var permission = await _service.GetDtoById(id);
            
            if(permission==null) return NotFound();

            return View(permission);
        }

        public async Task<IActionResult> Edit(string id){
            var permission = await _service.EditDto(id);
            if(permission == null) return NotFound();
            return View(permission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id,[Bind("Id","Name","Description")]PermissionEditDto dto){
            if(id != dto.Id) return NotFound();
            if(!ModelState.IsValid){
                TempData["Error_data"] ="El Intento de Actualizacion no Valido";
                return View("Edit",dto);
            }
            try{
                await _service.Update(dto);
            }catch(DbUpdateConcurrencyException){
                if(!_service.Exists(id)){
                    return NotFound();
                }else{
                    TempData["Error_data"] ="El Intento de Actualizacion no Valido";
                    throw ;
                }
            }
            TempData["Success_data"]="El permiso se a actualizado correctamente";
            return RedirectToAction(nameof(Index));
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

WebApp/Views/Permission/Edit.cshtml
@using WebApp.Dto.Permission;
@model PermissionEditDto;
@{
    ViewData["Title"] = "Editar Permiso "+Model.Name;
}

<h1>@ViewData["Title"]</h1>
@if(TempData["Error_data"]!= null){
    <div class="m-0 pt-2 row justify-content-center align-items-center">
        <div class="col-auto p-1 text-center">
            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                @TempData["Error_data"]
            </div>
        </div>
    </div>
}
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly"></div>
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Name)
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary"/>
                <a class="btn" asp-controller="Permission" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Permission/Index.cshtml
@using WebApp.Models;
@using WebApp.Data;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> user;
@model Pagination<Permission>;
@{
    ViewData["Title"] = "Permisos";
    var previousWeakened = !Model.previousPages ? "disabled":"";
    var nextWeakened = !Model.nextPages ? "disabled":"";
}
<h1>@ViewData["Title"]</h1>


@if(TempData["Success_data"]!= null){
    <div class="m-0 pt-2 row justify-content-center align-items-center">
        <div class="col-auto p-1 text-center">
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                @TempData["Success_data"]
            </div>
        </div>
    </div>
}

<form asp-controller="Category" asp-action="Index">
    <p>
        Buscar: <input type="text" name="search" value="@ViewData["FiltroActual"]" class="form-text"/>
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark"/>
        <a asp-action="Index" class="btn btn-outline-info">Lista Completa</a>
    </p>
</form>
<div class="table-responsive-md">
    <table class="table">
        <thead class="table-light">
            <tr>
                <th>Nombre</th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model){
                <tr>
                    <th>@Html.DisplayFor(modelItem=>item.Name)</th>
                    <th>
                        <div class="btn-group btn-group-sm">
                            <a asp-controller="Permission" asp-action="show" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Ver</a>
                            @if(User.IsInRole("Root")){
                                <a asp-controller="Permission" asp-action="Edit" asp-route-id="@item.Id" class="btn  btn-warning btn-sm">Editar</a>
                            }
                        </div>
                    </th>
                </tr>
            }
        </tbody>
    </table>
    @if(Model.pageSize>0){
        <nav>
        <ul class="pagination">
            <li class="page-item">
                <a asp-action="Index" class="page-link @previousWeakened" asp-route-numPage="@(Model.initPage-1)" >
                            <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            @for(var i=Model.startPage; i<=Model.endPage;i++){
                var activePage =(i==Model.initPage)? "active disable":"";
                <li class="page-item">
                    <a asp-action="Index" asp-route-numPage="@i" class="page-link @activePage">@i</a>
                </li>
            }
            <li class="page-item">
                <a  class="page-link @nextWeakened" asp-action="Index" asp-route-numPage="@(Model.initPage+1)">
                    <span aria-hidden="true" >&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    }
</div>

WebApp/Views/Permission/Show.cshtml
@using WebApp.Dto.Permission;
@model PermissionDetailDto;
@{
    ViewData["Title"] = "Permiso "+@Model.Name;
}

<h1>@ViewData["Title"]</h1>

<div class="m-0 row justify-content-start">
    <div class="p-2 col-auto">
        <blockquote class="blockquote">
            <h4 class="display-6">@Html.DisplayFor(modelItem=>Model.Name)</h4>
        </blockquote>
        <hr>
        <figure class="text-center">
            <blockquote class="blockquote">
                <h4 class="display-6">@Html.DisplayNameFor(modelItem=>Model.Description)</h4>
            </blockquote>
            <figcaption class="blockquote-footer">
                @Html.DisplayFor(modelItem => Model.Description)
            </figcaption> 
        </figure>
    </div>
</div>